### ISSUE TITLE
Implement Google OAuth Login and Logout

### ISSUE THREAD

**Issue by hakkilab** [CS467SynchronousCommunicationPlatform/frontend#1]
- [x] Create a login page that unauthenticated users are routed to
- [x] Use Google OAuth to login users, redirect them to chat page after login
- [x] Use Google OAuth to logout users, redirect them to login page after logout

**Comment by srt5228** [comment]
![image](https://github.com/user-attachments/assets/6c01a722-401f-4469-9bbc-f938b0ff192e)

**Comment by srt5228** [comment]
Interfaces have been completed - Actual Authentication work should be pushed to next progress report for Arberim
