### ISSUE TITLE
Implement Chat Page Skeleton

### ISSUE THREAD

**Issue by hakkilab** [CS467SynchronousCommunicationPlatform/frontend#2]
Implement basic chat user interface with fake data, matching planned chat UI below
![Image](https://github.com/user-attachments/assets/1d443507-5954-46be-86fc-83a73868ce76)

**Comment by srt5228** [comment]
UI from plan copied - focus will be on modularizing things like: 

- Channel Pane
- Chat Window
- Input Box
- Logout Button 
- User Pane
