### ISSUE TITLE
Channel Creation Issue

### ISSUE THREAD

**Issue by srt5228** [CS467SynchronousCommunicationPlatform/frontend#37]
When a new channel is created, a user cannot properly interact with the channel until a full page load has been performed.

**Comment by hakkilab** [comment]
Might be resolved, fixed an issue returning the create channel response that was causing rendering errors and an empty user list, check out https://github.com/CS467SynchronousCommunicationPlatform/frontend/commit/975e7915e75ecbcb64f3cf455a14d6a58464272f
